### ISSUE TITLE
Power9 support

### ISSUE THREAD

**Issue by snyrkill** [algesten/ureq#671]
I'm trying to build pgrx from source on Debian 12 on power9.
It fails on the ring.0.16.02 crate because that version does not support power9.
This has been fixed in the newest version (ring.0.17.2 or 3) 
According to the pgrx team:
_Looks like our dependency on ring is transient through our dependency on ureq (for cargo-pgrx). Also looks like our default is to use ureq/native-tls._
Would it be possible for you to update your dependancy tree?

**Comment by algesten** [comment]
```
$ cargo tree -i ring
ring v0.16.20
├── rustls v0.21.7
│   └── ureq v2.8.0 (/Users/martin/dev/ureq)
│   [dev-dependencies]
│   └── ureq v2.8.0 (/Users/martin/dev/ureq)
├── rustls-webpki v0.101.6
│   ├── rustls v0.21.7 (*)
│   └── ureq v2.8.0 (/Users/martin/dev/ureq)
└── sct v0.7.0
    └── rustls v0.21.7 (*)
```

Ring is a transitive dependency for ureq that comes from "rustls". What's sad is that rustls is built despite you using ureq/native-tls. This is because Rust's feature flags are additive, so if dependency A says "ureq with rustls" and B says "ureq with native-tls", we get an indeterminate TLS backend. We have instead opted for compiling both and making deciding which to use runtime. This decision is biting us here, because you simply can't get it to NOT compile rustls on Power9 despite it not being used.

I'm sorry to say there isn't a quick fix we can do here. We're already using the latest rustls release, and the Power9 build must be fixed in the rustls project. Changing the feature flag behavior would be a breaking change and require a major release.

I promise I'll monitor the rustls project to keep us tightly up-to-date, but the feature flag behavior is something we need to take with us into consideration for making a new major version in the future (it's the first time I encountered this).

My only suggestion is to stay on the previous version of ureq, for now.

**Comment by snyrkill** [comment]
Thanks Martin.
I checked rustls and it seems they have added ring.0.17.2 to Cargo.lock. 0.16.2 is still present though.
I know very little about Rust, I'm just a lowly DBA trying to install timescaledb-toolkit on Power9 and that endeavor has taken me here. 
Hopefully this will resolve itself in the future but as ring.0.16.2 is over 4 years old now I'm not too optimistic.
Anyway, thank you for explaining this to me.
Cheers,
-S

**Comment by algesten** [comment]
Closing since we're moving to ureq 3.x.
